# Build script used by gitlab.medelexis.ch
variables:
   ORIGIN_BRANCH: "target-2021-03-java11" 

stages:
    - build
    - trigger_other_builds

build:
  stage: build
  tags:
  - java11
  - maven
  script:
  - unset JAVA_HOME
  - env
  - xvfb-run mvn -V clean verify -B -Pall-archs -DelexisJcfsTest=true
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY_ED25519_BASE64" | base64 -d)
  - rsync -aiv --no-recursive -e ssh ch.elexis.core.p2site/target/products/* deploy@download.medelexis.ch:download.elexis.info/elexis/$CI_COMMIT_REF_NAME/products/
  - rsync -aiv --delete -e ssh ch.elexis.core.p2site/target/repository/ deploy@download.medelexis.ch:download.elexis.info/elexis/$CI_COMMIT_REF_NAME/p2/elexis-3-core/
  - eval $(ssh-agent -k)
  artifacts:
    reports:
      junit:
        - tests/**/target/surefire-reports/TEST-*.xml
  only:
  - master@elexis/elexis-3-core
  - /^\d*[.]\d*$/@elexis/elexis-3-core
  - /^[bf]\d*$/@elexis/elexis-3-core

trigger_elexis-3-base_build:
    stage: trigger_other_builds
    script:
    - "curl -X POST -F token=$TRIGGER_TOKEN_ELEXIS_3_BASE -F ref=$CI_COMMIT_REF_NAME https://gitlab.medelexis.ch/api/v4/projects/14/trigger/pipeline"
    only:
    - master@elexis/elexis-3-core
    - /^\d*[.]\d*$/@elexis/elexis-3-core
    - /^[bf]\d*$/@elexis/elexis-3-core
